common/models/News.php
<?php

namespace common\models;

use Yii;
use common\models\NewsCategoryRelations;

/**
 * This is the model class for table "news".
 *
 * @property integer $id
 * @property string $meta_keywords
 * @property string $meta_description
 * @property string $image
 * @property string $title
 * @property string $anons
 * @property string $text
 * @property string $publish_date
 * @property integer $status
 * @property string $created
 * @property string $updated
 */
class News extends \yii\db\ActiveRecord
{
    const STATUS_ACTIVE = 1;
    const STATUS_INACTIVE = 0;
    public $cats;
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%news}}';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['title', 'anons', 'text', 'publish_date'], 'required'],
            [['anons', 'text'], 'string'],
            [['publish_date', 'created', 'updated','cats'], 'safe'],
            [['status'], 'integer'],
            [['meta_keywords', 'meta_description', 'image', 'title'], 'string', 'max' => 255],
            [['image'], 'file', 'extensions' => 'png, jpg, jpeg, gif',],
        ];
    }
    /**
     * @inheritdoc
     */
    public static function statusLabels()
    {
        return [
            self::STATUS_ACTIVE => 'Активен',
            self::STATUS_INACTIVE => 'Не активен',
        ];
    }


    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'meta_keywords' => 'Meta Keywords',
            'meta_description' => 'Meta Description',
            'image' => 'Рисунок',
            'title' => 'Название',
            'anons' => 'Анонс',
            'text' => 'Полная статья',
            'publish_date' => 'Дата публикации',
            'status' => 'Активен/Не активен',
            'created' => 'Создан',
            'updated' => 'Обновлен',
            'cats' => 'Категории',
        ];
    }

    /**
     * @inheritdoc
     */
    public function afterSave($insert, $changedAttributes)
    {
        NewsCategoryRelations::deleteAll(['news_id'=>$this->id]);
        if($this->cats){
            foreach ($this->cats as $cat){
                $new = new NewsCategoryRelations();
                $new->news_id = $this->id;
                $new->category_id = $cat;
                $new->save();
            }
        }
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritdoc
     */
    public function afterFind()
    {

        $cats = NewsCategoryRelations::find()->where(['news_id' => $this->id])->all();
        $this->cats = [];
        if($cats){
            foreach ($cats as $cat){
                $this->cats[$cat->category_id]=$cat->category_id;
            }
        }

        parent::afterFind(); // TODO: Change the autogenerated stub
    }
}

backend/controllers/NewsController.php
<?php

namespace backend\controllers;

use Yii;
use common\models\News;
use common\models\search\NewsSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\UploadedFile;

/**
 * NewsController implements the CRUD actions for News model.
 */
class NewsController extends Controller
{
    /**
     * @inheritdoc
     */
    public function actions()
    {
        parent::actions();
        /*
         * "url" - это ссылка к директории с веб доступом в которой будет загружен
         * сам файл. Подразумевается что в конкретно данной ситуации загрузка происходит
         * в временную папку, по этому и УРЛ будет временным.
         * "path" - это путь к временной папке куда будет загружен файл. Данный
         * выджет имеет такую логику что он предварительно загружает файл в временную
         * папку, именно в той что указано в "path". И только при сохранении он
         * перемещает файл в постоянную папку.
         * надо указывать одну и туже папку
         */
        return [
            'image-upload' => [
                'class' => 'vova07\imperavi\actions\UploadAction',
                'url' => Yii::$app->params['news.path'].'/', // Directory URL address, where files are stored.
                'path' => Yii::$app->params['news.upload.path'] // Or absolute path to directory where files are stored.
            ],
            'images-get' => [
                'class' => 'vova07\imperavi\actions\GetAction',
                'url' => Yii::$app->params['news.path'].'/', // Directory URL address, where files are stored.
                'path' => Yii::$app->params['news.upload.path'], // Or absolute path to directory where files are stored.
                'type' => \vova07\imperavi\actions\GetAction::TYPE_IMAGES,
            ],
        ];
    }
    
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all News models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new NewsSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single News model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new News model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new News();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            
            $file = UploadedFile::getInstance($model, 'image');
            if ($file) {
                $patch = Yii::$app->params['news.upload.path'];
                $model->image = time() . '_' . md5($file->baseName) . '.' . $file->extension;
                $file->saveAs($patch . '/' . $model->image);
            }
            if ($model->save()) {
                return $this->redirect(['view', 'id' => $model->id]);
            }
            
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing News model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        $filename = $model->image;
        if ($model->load(Yii::$app->request->post())) {
            $file = UploadedFile::getInstance($model, 'image');
            if ($file) {
                $patch = Yii::$app->params['news.upload.path'];
                $model->image = time() . '_' . md5($file->baseName) . '.' . $file->extension;
                $file->saveAs($patch . '/' . $model->image);
            } elseif ($filename) {
                $model->image = $filename;
            }
            if($model->save()){
                return $this->redirect(['view', 'id' => $model->id]);
            }
           
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing News model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the News model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return News the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = News::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

frontend/controllers/NewsController.php
<?php
namespace frontend\controllers;

use common\models\News;
use common\models\NewsCategory;
use yii\data\ActiveDataProvider;
use yii\web\NotFoundHttpException;

/**
 * News controller
 */
class NewsController extends \yii\web\Controller
{
    public function actionCategory()
    {
        $dataProvider = new ActiveDataProvider([
            'query' =>NewsCategory::find()
                ->where(['status'=>News::STATUS_ACTIVE])
                ->orderBy('id DESC'),
            'pagination' => [
                'pageSize' => 10,
            ],
        ]);
        $this->view->title = 'Категории';
        return $this->render('category', ['listDataProvider' => $dataProvider]); 
    }

    /**
     * News items for category.
     *
     * @return mixed
     */
    public function actionCatView($id)
    {
        $cat = NewsCategory::findOne($id);
        if($cat==null)
        {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
        $dataProvider = new ActiveDataProvider([
            'query' => News::find()
                ->leftJoin('tst_news_category_relations','tst_news.id=tst_news_category_relations.news_id')
                ->where('tst_news_category_relations.category_id=:id AND status=:status',[':id'=>(int)$id,':status'=>News::STATUS_ACTIVE])
                ->orderBy('id DESC'),
            'pagination' => [
                'pageSize' => 10,
            ],
        ]);
        $this->view->title = 'Статьи категорию: '.$cat->title;
        return $this->render('cat-view', ['listDataProvider' => $dataProvider]);
    }
    /**
     * News items.
     *
     * @return mixed
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => News::find()
                ->where(['status'=>News::STATUS_ACTIVE])
                ->orderBy('id DESC'),
            'pagination' => [
                'pageSize' => 10,
            ],
        ]);
        $this->view->title = 'Статьи';
        return $this->render('index', ['listDataProvider' => $dataProvider]);
    }

    /**
     * News item view.
     *
     * @return mixed
     */
    public function actionView($id)
    {
        if (($model = News::find()->where('id=:id AND status=:status',[':id'=>(int)$id,':status'=>News::STATUS_ACTIVE])->one()) !== null)
        {
            return $this->render('view',
                ['model'=>$model]
            );
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
        
    }

}

frontend/views/news/_list.php
<?php
/**
 * Created by PhpStorm.
 * User: Ulugbek
 * Date: 10.02.2017
 * Time: 12:36
 * @var $model common\models\News
 */
use yii\helpers\Html;
use yii\helpers\HtmlPurifier;
?>


<div class="news-item">
    <h2><?= Html::encode($model->title) ?></h2>
    <?= HtmlPurifier::process($model->anons) ?>
    <p><?=\yii\helpers\Html::a('Читать дальше &raquo;',\yii\helpers\Url::to(['news/view','id'=>$model->id]),['class'=>'btn btn-default'])?></p>
</div>

frontend/views/news/_list_category.php
<?php
/**
 * Created by PhpStorm.
 * User: Ulugbek
 * Date: 10.02.2017
 * Time: 12:36
 * @var $model common\models\NewsCategory
 */
use yii\helpers\Html;
use yii\helpers\HtmlPurifier;
?>


<div class="news-item">
    <h2><?= Html::encode($model->title) ?></h2>
    <?= HtmlPurifier::process($model->description) ?>
    <p><?=\yii\helpers\Html::a('Посмотрить новости &raquo;',\yii\helpers\Url::to(['news/cat-view','id'=>$model->id]),['class'=>'btn btn-default'])?></p>
</div>

frontend/views/news/cat-view.php
<?php
/* @var $this yii\web\View */
use yii\widgets\ListView;
?>
<h1><?=$this->title?></h1>

<?= ListView::widget([
    'dataProvider' => $listDataProvider,
    'itemView' => '_list',
    'emptyText' => 'Список пуст',
    'pager' => [
        'firstPageLabel' => 'Первая',
        'lastPageLabel' => 'Последняя',
        'nextPageLabel' => 'Следующая',
        'prevPageLabel' => 'Предыдущая',
        'maxButtonCount' => 5,
    ],
    'layout' => "{pager}\n{items}\n{pager}",//\n{summary}
    'summary' => 'Показано {count} из {totalCount}',
    'summaryOptions' => [
        'tag' => 'span',
        'class' => 'my-summary'
    ],
]);

frontend/views/news/category.php
<?php
/* @var $this yii\web\View */
use yii\widgets\ListView;
?>
    <h1><?=$this->title?></h1>

<?= ListView::widget([
    'dataProvider' => $listDataProvider,
    'itemView' => '_list_category',
    'emptyText' => 'Список пуст',
    'pager' => [
        'firstPageLabel' => 'Первая',
        'lastPageLabel' => 'Последняя',
        'nextPageLabel' => 'Следующая',
        'prevPageLabel' => 'Предыдущая',
        'maxButtonCount' => 5,
    ],
    'layout' => "{pager}\n{items}\n{pager}",//\n{summary}
    'summary' => 'Показано {count} из {totalCount}',
    'summaryOptions' => [
        'tag' => 'span',
        'class' => 'my-summary'
    ],
]);

frontend/views/news/index.php
<?php
/* @var $this yii\web\View */
use yii\widgets\ListView;
?>
<h1><?=$this->title?></h1>

<?= ListView::widget([
    'dataProvider' => $listDataProvider,
    'itemView' => '_list',
    'emptyText' => 'Список пуст',
    'pager' => [
        'firstPageLabel' => 'Первая',
        'lastPageLabel' => 'Последняя',
        'nextPageLabel' => 'Следующая',
        'prevPageLabel' => 'Предыдущая',
        'maxButtonCount' => 5,
    ],
    'layout' => "{pager}\n{items}\n{pager}",//\n{summary}
    'summary' => 'Показано {count} из {totalCount}',
    'summaryOptions' => [
        'tag' => 'span',
        'class' => 'my-summary'
    ],
]);

frontend/views/news/view.php
<?php
/* @var $this yii\web\View */
$this->title = $model->title;
?>
<h1><?=$this->title?></h1>

<?php if(!empty($model->image))
{?>
   <div><img src="/uploads/news/<?=$model->image?>" alt=""></div> 
<?php } ?>
<p>
    <?=$model->text?>
</p>